# Generated by Django 5.2.1 on 2025-05-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classificationresult_remove_item_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationresult',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
    ]
